// ─── Video Template Definitions ───

export const VIDEO_CATEGORIES = [
  { key: 'trending', emoji: '🔥', name: 'Trending', nameEs: 'Trending' },
  { key: 'love', emoji: '💕', name: 'Love & Cute', nameEs: 'Amor y Ternura' },
  { key: 'funny', emoji: '😂', name: 'Funny', nameEs: 'Divertidos' },
  { key: 'movies', emoji: '🎬', name: 'Movies & TV', nameEs: 'Peliculas y TV' },
  { key: 'epic', emoji: '⚔️', name: 'Epic & Fantasy', nameEs: 'Epico y Fantasia' },
  { key: 'music', emoji: '🎵', name: 'Music', nameEs: 'Musica' },
  { key: 'social', emoji: '📱', name: 'Social Media', nameEs: 'Redes Sociales' },
  { key: 'seasonal', emoji: '🎄', name: 'Seasonal', nameEs: 'Temporada' },
  { key: 'custom', emoji: '✨', name: 'Custom', nameEs: 'Personalizado' },
]

export const VIDEO_TEMPLATES = [
  // ─── TRENDING ───
  {
    id: 'good-morning',
    category: 'trending',
    name: 'Good Morning!',
    nameEs: 'Buenos Dias!',
    emoji: '☀️',
    description: 'Your pet says good morning to the camera',
    descriptionEs: 'Tu mascota dice buenos dias a la camara',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Good morning everyone! Rise and shine, it\'s a beautiful day!', es: 'Buenos dias a todos! Arriba y a brillar, es un hermoso dia!' },
  },
  {
    id: 'i-love-you',
    category: 'trending',
    name: 'I Love You',
    nameEs: 'Te Quiero',
    emoji: '❤️',
    description: 'Your pet confesses their love',
    descriptionEs: 'Tu mascota confiesa su amor',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Hey you! Yes, you. I just wanted to say... I love you so much!', es: 'Oye tu! Si, tu. Solo queria decirte... Te quiero mucho!' },
  },
  {
    id: 'happy-birthday',
    category: 'trending',
    name: 'Happy Birthday',
    nameEs: 'Feliz Cumpleanos',
    emoji: '🎂',
    description: 'Birthday wishes from your pet',
    descriptionEs: 'Felicitaciones de cumpleanos de tu mascota',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Happy birthday to you! You\'re the best human ever! Where\'s my slice of cake?', es: 'Feliz cumpleanos! Eres el mejor humano del mundo! Donde esta mi pedazo de pastel?' },
  },
  {
    id: 'treat-please',
    category: 'trending',
    name: 'Give Me a Treat',
    nameEs: 'Dame un Premio',
    emoji: '🦴',
    description: 'Your pet begs for a treat',
    descriptionEs: 'Tu mascota pide un premio',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Excuse me? Hello? I\'ve been a very good boy. I think I deserve a treat. Actually, make it two.', es: 'Disculpa? Hola? He sido muy buen chico. Creo que merezco un premio. De hecho, que sean dos.' },
  },
  {
    id: 'miss-you',
    category: 'trending',
    name: 'I Miss You',
    nameEs: 'Te Extrano',
    emoji: '🥺',
    description: 'Your pet misses someone special',
    descriptionEs: 'Tu mascota extrana a alguien especial',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Hey... I just wanted you to know that I miss you so much. Come home soon, okay?', es: 'Oye... solo queria que supieras que te extrano mucho. Ven pronto a casa, si?' },
  },
  {
    id: 'thank-you',
    category: 'trending',
    name: 'Thank You',
    nameEs: 'Gracias',
    emoji: '🙏',
    description: 'A heartfelt thank you from your pet',
    descriptionEs: 'Un agradecimiento sincero de tu mascota',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'I just want to say thank you. For everything. You\'re my whole world and I\'m so lucky to have you.', es: 'Solo quiero darte las gracias. Por todo. Eres mi mundo entero y soy muy afortunado de tenerte.' },
  },
  {
    id: 'monday-mood',
    category: 'trending',
    name: 'Monday Mood',
    nameEs: 'Humor de Lunes',
    emoji: '😩',
    description: 'Your pet hates Mondays too',
    descriptionEs: 'Tu mascota tambien odia los lunes',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'It\'s Monday again?! Ugh. I don\'t want to get out of bed. Five more minutes... or hours.', es: 'Es lunes otra vez?! Ugh. No me quiero levantar. Cinco minutos mas... o horas.' },
  },
  {
    id: 'walk-time',
    category: 'trending',
    name: 'Walk Time!',
    nameEs: 'Hora del Paseo!',
    emoji: '🐕',
    description: 'Your pet is excited for their walk',
    descriptionEs: 'Tu mascota esta emocionada por su paseo',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Did someone say WALK?! Oh my god oh my god! Let\'s go let\'s go let\'s GO!', es: 'Alguien dijo PASEO?! Dios mio dios mio! Vamos vamos VAMOS!' },
  },
  {
    id: 'sorry-human',
    category: 'trending',
    name: 'I\'m Sorry',
    nameEs: 'Lo Siento',
    emoji: '😔',
    description: 'Your pet apologizes for being naughty',
    descriptionEs: 'Tu mascota se disculpa por portarse mal',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Okay... I know I ate your shoe. And maybe the couch cushion. I\'m really sorry. Still love me?', es: 'Okay... se que me comi tu zapato. Y quizas el cojin del sofa. Lo siento mucho. Aun me quieres?' },
  },
  {
    id: 'new-year',
    category: 'trending',
    name: 'Happy New Year',
    nameEs: 'Feliz Ano Nuevo',
    emoji: '🎆',
    description: 'New Year wishes from your pet',
    descriptionEs: 'Deseos de ano nuevo de tu mascota',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Happy New Year! My resolution is more treats, more walks, and more cuddles. What\'s yours?', es: 'Feliz Ano Nuevo! Mi resolucion es mas premios, mas paseos y mas abrazos. Cual es la tuya?' },
  },

  // ─── LOVE & CUTE ───
  {
    id: 'be-mine',
    category: 'love',
    name: 'Be My Valentine',
    nameEs: 'Se Mi San Valentin',
    emoji: '💝',
    description: 'Valentine\'s Day message from your pet',
    descriptionEs: 'Mensaje de San Valentin de tu mascota',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Will you be my valentine? I promise to love you fur-ever! Get it? Fur-ever?', es: 'Quieres ser mi San Valentin? Prometo amarte por siempre! Para siempre siempre!' },
  },
  {
    id: 'cuddle-time',
    category: 'love',
    name: 'Cuddle Time',
    nameEs: 'Hora de Abrazos',
    emoji: '🤗',
    description: 'Your pet wants snuggles',
    descriptionEs: 'Tu mascota quiere acurrucarse',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Come here. It\'s cuddle time. No, you can\'t say no. I\'m too adorable. Get over here!', es: 'Ven aqui. Es hora de abrazos. No, no puedes decir que no. Soy muy adorable. Ven aca!' },
  },
  {
    id: 'mom-love',
    category: 'love',
    name: 'Love You Mom',
    nameEs: 'Te Quiero Mama',
    emoji: '👩',
    description: 'Special message for mom',
    descriptionEs: 'Mensaje especial para mama',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Mom, you\'re the best person in the whole world. Thanks for feeding me and loving me. You\'re my favorite human!', es: 'Mama, eres la mejor persona del mundo. Gracias por alimentarme y quererme. Eres mi humana favorita!' },
  },
  {
    id: 'dad-love',
    category: 'love',
    name: 'Love You Dad',
    nameEs: 'Te Quiero Papa',
    emoji: '👨',
    description: 'Special message for dad',
    descriptionEs: 'Mensaje especial para papa',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Dad! You\'re my best buddy. Remember when you snuck me that extra treat? That was awesome. Love you, man!', es: 'Papa! Eres mi mejor amigo. Recuerdas cuando me diste ese premio extra? Fue increible. Te quiero!' },
  },
  {
    id: 'best-friend',
    category: 'love',
    name: 'Best Friends Forever',
    nameEs: 'Mejores Amigos',
    emoji: '👯',
    description: 'Your pet celebrates your friendship',
    descriptionEs: 'Tu mascota celebra su amistad',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'You\'re not just my owner, you\'re my best friend. We\'re in this together, forever!', es: 'No eres solo mi dueno, eres mi mejor amigo. Estamos juntos en esto, para siempre!' },
  },
  {
    id: 'goodnight',
    category: 'love',
    name: 'Goodnight',
    nameEs: 'Buenas Noches',
    emoji: '🌙',
    description: 'Sweet goodnight message',
    descriptionEs: 'Dulce mensaje de buenas noches',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Goodnight! Sweet dreams. I\'ll be right here when you wake up. Probably on your pillow. Sorry not sorry.', es: 'Buenas noches! Dulces suenos. Estare aqui cuando despiertes. Probablemente en tu almohada. No me arrepiento.' },
  },
  {
    id: 'get-well',
    category: 'love',
    name: 'Get Well Soon',
    nameEs: 'Mejorate Pronto',
    emoji: '🤒',
    description: 'Feel better message from your pet',
    descriptionEs: 'Mensaje de mejorate de tu mascota',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'I heard you\'re not feeling well. I\'m sending you healing licks and warm snuggles. Get better soon!', es: 'Escuche que no te sientes bien. Te mando lamidas curativas y abrazos calentitos. Mejorate pronto!' },
  },
  {
    id: 'adoption-day',
    category: 'love',
    name: 'Adoption Day',
    nameEs: 'Dia de Adopcion',
    emoji: '🏠',
    description: 'Celebrating the day you became family',
    descriptionEs: 'Celebrando el dia que se volvieron familia',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Remember when you chose me? Best day of my life. Every day since then has been amazing. Thank you for saving me.', es: 'Recuerdas cuando me elegiste? El mejor dia de mi vida. Cada dia desde entonces ha sido increible. Gracias por salvarme.' },
  },
  {
    id: 'jealous',
    category: 'love',
    name: 'Are You Cheating?',
    nameEs: 'Me Enganas?',
    emoji: '😤',
    description: 'Your pet smells another pet on you',
    descriptionEs: 'Tu mascota huele otra mascota en ti',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Wait. I smell another dog on you. WHO IS SHE?! I mean... I\'m not jealous or anything...', es: 'Espera. Huelo otro perro en ti. QUIEN ES?! Digo... no estoy celoso ni nada...' },
  },
  {
    id: 'forever-home',
    category: 'love',
    name: 'My Forever Home',
    nameEs: 'Mi Hogar Para Siempre',
    emoji: '🏡',
    description: 'Grateful for their forever home',
    descriptionEs: 'Agradecido por su hogar para siempre',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'I finally found my forever home. With you. And I wouldn\'t trade it for all the treats in the world.', es: 'Finalmente encontre mi hogar para siempre. Contigo. Y no lo cambiaria por todos los premios del mundo.' },
  },

  // ─── FUNNY ───
  {
    id: 'ate-homework',
    category: 'funny',
    name: 'Ate the Homework',
    nameEs: 'Me Comi la Tarea',
    emoji: '📝',
    description: 'Your pet explains the homework situation',
    descriptionEs: 'Tu mascota explica la situacion de la tarea',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'So about your homework... it looked delicious. I regret nothing. Actually, I regret the staples.', es: 'Sobre tu tarea... se veia deliciosa. No me arrepiento de nada. Bueno, de las grapas si.' },
  },
  {
    id: 'tax-advice',
    category: 'funny',
    name: 'Tax Advice',
    nameEs: 'Consejo Fiscal',
    emoji: '💰',
    description: 'Your pet gives financial advice',
    descriptionEs: 'Tu mascota da consejos financieros',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Listen, I\'m not a financial advisor, but I think you should invest all your money in treats. Trust me on this.', es: 'Mira, no soy asesor financiero, pero creo que deberias invertir todo tu dinero en premios. Confía en mi.' },
  },
  {
    id: 'vet-review',
    category: 'funny',
    name: 'Vet Visit Review',
    nameEs: 'Resena del Veterinario',
    emoji: '🏥',
    description: 'Your pet reviews their vet experience',
    descriptionEs: 'Tu mascota resena su visita al veterinario',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'One star. Would not recommend. They poked me, weighed me, and had the audacity to say I\'m overweight. Rude!', es: 'Una estrella. No lo recomiendo. Me pincharon, me pesaron, y tuvieron el descaro de decir que estoy gordito. Groseros!' },
  },
  {
    id: 'squirrel',
    category: 'funny',
    name: 'SQUIRREL!',
    nameEs: 'ARDILLA!',
    emoji: '🐿️',
    description: 'Your pet spots a squirrel',
    descriptionEs: 'Tu mascota ve una ardilla',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'So I was just sitting there, minding my own business, when suddenly— SQUIRREL! Sorry, what was I saying?', es: 'Entonces estaba ahi sentado, en mis asuntos, cuando de repente— ARDILLA! Perdon, que estaba diciendo?' },
  },
  {
    id: 'diet',
    category: 'funny',
    name: 'On a Diet',
    nameEs: 'A Dieta',
    emoji: '🥗',
    description: 'Your pet is NOT happy about their diet',
    descriptionEs: 'Tu mascota NO esta contenta con su dieta',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Day three of this diet. I\'ve lost zero pounds and all of my will to live. Please. Just one treat. I\'m begging.', es: 'Dia tres de esta dieta. He perdido cero kilos y toda mi voluntad de vivir. Por favor. Solo un premio. Te lo ruego.' },
  },
  {
    id: 'bath-time',
    category: 'funny',
    name: 'Bath Time Horror',
    nameEs: 'Horror del Bano',
    emoji: '🛁',
    description: 'Your pet\'s dramatic bath experience',
    descriptionEs: 'La dramatica experiencia de bano de tu mascota',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'They\'re running the bath water. This is it. Tell my toys I love them. If I don\'t make it, remember me as I was.', es: 'Estan abriendo el agua del bano. Este es el fin. Diganle a mis juguetes que los quiero. Si no lo logro, recuerdenme como fui.' },
  },
  {
    id: 'mailman',
    category: 'funny',
    name: 'The Mailman',
    nameEs: 'El Cartero',
    emoji: '📬',
    description: 'Your pet vs the mailman',
    descriptionEs: 'Tu mascota vs el cartero',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'HE\'S BACK. The mailman is back. I bark every single day and he still comes. What is this guy\'s problem?!', es: 'VOLVIO. El cartero volvio. Le ladro todos los dias y sigue viniendo. Cual es el problema de este tipo?!' },
  },
  {
    id: 'couch-thief',
    category: 'funny',
    name: 'Couch Thief',
    nameEs: 'Ladron del Sofa',
    emoji: '🛋️',
    description: 'Your pet stole your spot on the couch',
    descriptionEs: 'Tu mascota robo tu lugar en el sofa',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Oh, is this your spot? That\'s interesting because I don\'t see your name on it. Possession is nine-tenths of the law.', es: 'Ah, este es tu lugar? Interesante porque no veo tu nombre aqui. La posesion es nueve decimos de la ley.' },
  },
  {
    id: 'food-critic',
    category: 'funny',
    name: 'Food Critic',
    nameEs: 'Critico de Comida',
    emoji: '🍽️',
    description: 'Your pet reviews their dinner',
    descriptionEs: 'Tu mascota resena su cena',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Tonight\'s dinner: same kibble as yesterday. Presentation? Lazy. Flavor? I ate it in three seconds so I guess it was fine.', es: 'La cena de hoy: la misma croqueta de ayer. Presentacion? Floja. Sabor? Me la comi en tres segundos asi que supongo que estuvo bien.' },
  },
  {
    id: 'zoomies',
    category: 'funny',
    name: 'The Zoomies',
    nameEs: 'Los Zoomies',
    emoji: '💨',
    description: 'Your pet explains the zoomies',
    descriptionEs: 'Tu mascota explica los zoomies',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Sometimes the energy just hits and I HAVE to run. Around the couch, through the kitchen, back again. I don\'t make the rules!', es: 'A veces la energia simplemente llega y TENGO que correr. Alrededor del sofa, por la cocina, y de regreso. Yo no hago las reglas!' },
  },

  // ─── MOVIES & TV ───
  {
    id: 'godfather',
    category: 'movies',
    name: 'The Dogfather',
    nameEs: 'El Perrino',
    emoji: '🎩',
    description: 'Your pet makes an offer you can\'t refuse',
    descriptionEs: 'Tu mascota hace una oferta irrechazable',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'I\'m gonna make you an offer you can\'t refuse. Give me the treat... and nobody gets their shoes chewed.', es: 'Te voy a hacer una oferta que no puedes rechazar. Dame el premio... y nadie tendra sus zapatos mordidos.' },
  },
  {
    id: 'titanic',
    category: 'movies',
    name: 'Titanic Scene',
    nameEs: 'Escena del Titanic',
    emoji: '🚢',
    description: 'Your pet is king of the world',
    descriptionEs: 'Tu mascota es el rey del mundo',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'I\'m the king of the world! Actually, I\'m the king of this couch. Same thing, really.', es: 'Soy el rey del mundo! Bueno, soy el rey de este sofa. Es lo mismo, la verdad.' },
  },
  {
    id: 'star-wars',
    category: 'movies',
    name: 'Use the Force',
    nameEs: 'Usa la Fuerza',
    emoji: '⭐',
    description: 'Your pet is a Jedi master',
    descriptionEs: 'Tu mascota es un maestro Jedi',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'The Force is strong with this one. I can sense your treat through the pantry door. This is the way.', es: 'La Fuerza es fuerte en este. Puedo sentir tu premio a traves de la puerta de la despensa. Este es el camino.' },
  },
  {
    id: 'james-bond',
    category: 'movies',
    name: 'Secret Agent',
    nameEs: 'Agente Secreto',
    emoji: '🕵️',
    description: 'Your pet is a secret agent',
    descriptionEs: 'Tu mascota es un agente secreto',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'The name is Woof. James Woof. I like my water bowl shaken, not stirred.', es: 'El nombre es Guau. James Guau. Me gusta mi tazon de agua agitado, no revuelto.' },
  },
  {
    id: 'harry-potter',
    category: 'movies',
    name: 'Hogwarts Letter',
    nameEs: 'Carta de Hogwarts',
    emoji: '🧙',
    description: 'Your pet got their Hogwarts letter',
    descriptionEs: 'Tu mascota recibio su carta de Hogwarts',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'I got my Hogwarts letter! I\'m a wizard, Harry! Wait, I\'m also Harry. This is confusing. Expecto Treat-onum!', es: 'Recibi mi carta de Hogwarts! Soy un mago, Harry! Espera, tambien soy Harry. Esto es confuso. Expecto Premio-num!' },
  },
  {
    id: 'jurassic',
    category: 'movies',
    name: 'Jurassic Park',
    nameEs: 'Parque Jurasico',
    emoji: '🦕',
    description: 'Your pet discovers dinosaurs',
    descriptionEs: 'Tu mascota descubre dinosaurios',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Life, uh, finds a way. And so does my nose when there\'s food anywhere in a five mile radius.', es: 'La vida, eh, encuentra un camino. Y tambien mi nariz cuando hay comida en un radio de cinco kilometros.' },
  },
  {
    id: 'avengers',
    category: 'movies',
    name: 'Avengers Assemble',
    nameEs: 'Avengers Unidos',
    emoji: '🦸',
    description: 'Your pet joins the Avengers',
    descriptionEs: 'Tu mascota se une a los Avengers',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'I am inevitable... ly going to need more treats. Also, I could do this all day. Especially napping. I could nap all day.', es: 'Soy inevitable... mente voy a necesitar mas premios. Tambien, puedo hacer esto todo el dia. Especialmente dormir.' },
  },
  {
    id: 'matrix',
    category: 'movies',
    name: 'The Matrix',
    nameEs: 'La Matrix',
    emoji: '💊',
    description: 'Your pet takes the red pill',
    descriptionEs: 'Tu mascota toma la pastilla roja',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'What if I told you... that the red dot from the laser pointer isn\'t real? I know it\'s hard to accept. But we must be strong.', es: 'Que tal si te dijera... que el punto rojo del laser no es real? Se que es dificil de aceptar. Pero debemos ser fuertes.' },
  },
  {
    id: 'disney-princess',
    category: 'movies',
    name: 'Disney Princess',
    nameEs: 'Princesa Disney',
    emoji: '👸',
    description: 'Your pet is a Disney princess',
    descriptionEs: 'Tu mascota es una princesa Disney',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'One day my prince will come. Or the mailman. Honestly at this point I\'ll take either one.', es: 'Un dia mi principe vendra. O el cartero. Honestamente a este punto me conformo con cualquiera.' },
  },
  {
    id: 'rocky',
    category: 'movies',
    name: 'Rocky Training',
    nameEs: 'Entrenamiento Rocky',
    emoji: '🥊',
    description: 'Your pet in Rocky training montage',
    descriptionEs: 'Tu mascota en montaje de entrenamiento Rocky',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Yo Adrian! I did it! I climbed all the stairs! Okay, it was only three steps to the porch, but still. Victory!', es: 'Yo Adrian! Lo logre! Subi todas las escaleras! Bueno, solo fueron tres escalones al porche, pero aun asi. Victoria!' },
  },

  // ─── EPIC & FANTASY ───
  {
    id: 'dragon-rider',
    category: 'epic',
    name: 'Dragon Rider',
    nameEs: 'Jinete de Dragon',
    emoji: '🐉',
    description: 'Your pet rides a dragon',
    descriptionEs: 'Tu mascota monta un dragon',
    type: 'scene',
    duration: 5,
    credits: 1,
    scenePrompt: 'This pet riding a majestic dragon through clouds, dramatic sunset, epic fantasy scene, 9:16 vertical video',
  },
  {
    id: 'knight',
    category: 'epic',
    name: 'Noble Knight',
    nameEs: 'Caballero Noble',
    emoji: '⚔️',
    description: 'Your pet in shining armor',
    descriptionEs: 'Tu mascota en armadura brillante',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'For honor! For glory! For... is that bacon? Sorry, where was I? Oh yes, FOR GLORY!', es: 'Por el honor! Por la gloria! Por... eso es tocino? Perdon, donde iba? Ah si, POR LA GLORIA!' },
  },
  {
    id: 'wizard-battle',
    category: 'epic',
    name: 'Wizard Battle',
    nameEs: 'Batalla de Magos',
    emoji: '🧙‍♂️',
    description: 'Your pet casts a powerful spell',
    descriptionEs: 'Tu mascota lanza un hechizo poderoso',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'You dare challenge me?! I am the most powerful wizard in all the land! Behold my power! BARK-adabra!', es: 'Te atreves a retarme?! Soy el mago mas poderoso de toda la tierra! Contempla mi poder! GUAU-cadabra!' },
  },
  {
    id: 'pirate-captain',
    category: 'epic',
    name: 'Pirate Captain',
    nameEs: 'Capitan Pirata',
    emoji: '🏴‍☠️',
    description: 'Your pet is a fearsome pirate',
    descriptionEs: 'Tu mascota es un pirata temible',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Arr! All paws on deck! We sail at dawn for the legendary island of infinite treats! Raise the bark flag!', es: 'Arr! Todas las patas a cubierta! Zarpamos al amanecer hacia la isla legendaria de los premios infinitos!' },
  },
  {
    id: 'superhero',
    category: 'epic',
    name: 'Superhero',
    nameEs: 'Superheroe',
    emoji: '🦸',
    description: 'Your pet discovers their superpowers',
    descriptionEs: 'Tu mascota descubre sus superpoderes',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'With great power comes great responsibility. My power? Being cute. My responsibility? Getting all the treats.', es: 'Con un gran poder viene una gran responsabilidad. Mi poder? Ser lindo. Mi responsabilidad? Obtener todos los premios.' },
  },
  {
    id: 'viking',
    category: 'epic',
    name: 'Viking Warrior',
    nameEs: 'Guerrero Vikingo',
    emoji: '🪓',
    description: 'Your pet conquers as a Viking',
    descriptionEs: 'Tu mascota conquista como Vikingo',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'SKOL! Tonight we feast! Bring me the finest meats! And maybe a belly rub. Vikings like belly rubs too.', es: 'SKOL! Esta noche festejamos! Traigan las mejores carnes! Y quizas una sobada de panza. A los vikingos tambien les gustan.' },
  },
  {
    id: 'space-commander',
    category: 'epic',
    name: 'Space Commander',
    nameEs: 'Comandante Espacial',
    emoji: '🚀',
    description: 'Your pet commands a starship',
    descriptionEs: 'Tu mascota comanda una nave espacial',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Captain\'s log, star date: treat o\'clock. We\'ve encountered a new civilization. They have snacks. Initiating first contact.', es: 'Bitacora del capitan, fecha estelar: hora del premio. Hemos encontrado una nueva civilizacion. Tienen snacks. Iniciando primer contacto.' },
  },
  {
    id: 'ninja',
    category: 'epic',
    name: 'Shadow Ninja',
    nameEs: 'Ninja Sombra',
    emoji: '🥷',
    description: 'Your pet is a stealth ninja',
    descriptionEs: 'Tu mascota es un ninja sigiloso',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'You cannot see me. I am one with the shadows. I am invisible. I am— okay fine, I knocked over the lamp. But NINJA STYLE!', es: 'No puedes verme. Soy uno con las sombras. Soy invisible. Soy— ok, tire la lampara. Pero EN ESTILO NINJA!' },
  },

  // ─── MUSIC ───
  {
    id: 'rapper',
    category: 'music',
    name: 'Rap Star',
    nameEs: 'Estrella de Rap',
    emoji: '🎤',
    description: 'Your pet drops bars',
    descriptionEs: 'Tu mascota suelta rimas',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Yo! My name is Woof and I\'m here to say, I love treats and naps every single day! Drop the mic!', es: 'Yo! Me llamo Guau y les vengo a decir, amo los premios y las siestas sin fin! Suelto el mic!' },
  },
  {
    id: 'opera-singer',
    category: 'music',
    name: 'Opera Star',
    nameEs: 'Estrella de Opera',
    emoji: '🎭',
    description: 'Your pet performs at the opera',
    descriptionEs: 'Tu mascota se presenta en la opera',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Ahem. Mi, mi, mi, mi... AROOOOOOO! Thank you, thank you. I\'ll be here all week. Tip your waiter.', es: 'Ejem. Mi, mi, mi, mi... AUUUUUUU! Gracias, gracias. Estare aqui toda la semana.' },
  },
  {
    id: 'rock-star',
    category: 'music',
    name: 'Rock Legend',
    nameEs: 'Leyenda del Rock',
    emoji: '🎸',
    description: 'Your pet rocks out on stage',
    descriptionEs: 'Tu mascota rockea en el escenario',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Hello Cleveland! Are you ready to ROCK?! This next song is called "Who\'s a Good Boy" and it\'s about ME!', es: 'Hola Mexico! Estan listos para ROCKEAR?! La siguiente cancion se llama "Quien es Buen Chico" y es sobre MI!' },
  },
  {
    id: 'dj',
    category: 'music',
    name: 'DJ Pet',
    nameEs: 'DJ Mascota',
    emoji: '🎧',
    description: 'Your pet drops the beat',
    descriptionEs: 'Tu mascota pone el beat',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'DJ Woofington in the house! Put your paws up! Boots and cats and boots and cats! WOOF WOOF!', es: 'DJ Guaufington en la casa! Levanten las patas! Bum tss bum tss! GUAU GUAU!' },
  },
  {
    id: 'country',
    category: 'music',
    name: 'Country Song',
    nameEs: 'Cancion Country',
    emoji: '🤠',
    description: 'Your pet sings a country ballad',
    descriptionEs: 'Tu mascota canta una balada country',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'I lost my bone, I lost my toy, my human left for work today... This is the saddest country song ever written. By a dog.', es: 'Perdi mi hueso, perdi mi juguete, mi humano se fue a trabajar... Esta es la cancion country mas triste jamas escrita. Por un perro.' },
  },

  // ─── SOCIAL MEDIA ───
  {
    id: 'influencer',
    category: 'social',
    name: 'Pet Influencer',
    nameEs: 'Pet Influencer',
    emoji: '📸',
    description: 'Your pet is a social media star',
    descriptionEs: 'Tu mascota es estrella de redes',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Hey besties! Don\'t forget to like, subscribe, and give me treats! Use code GOODBOY for ten percent off!', es: 'Hola amigos! No olviden dar like, suscribirse, y darme premios! Usen el codigo BUENCHICO para diez por ciento de descuento!' },
  },
  {
    id: 'asmr',
    category: 'social',
    name: 'ASMR Eating',
    nameEs: 'ASMR Comiendo',
    emoji: '🎙️',
    description: 'ASMR of your pet eating',
    descriptionEs: 'ASMR de tu mascota comiendo',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Welcome to my ASMR channel. Today I\'ll be eating kibble... very... slowly... crunch... crunch... crunch...', es: 'Bienvenidos a mi canal de ASMR. Hoy voy a comer croquetas... muy... lentamente... crunch... crunch... crunch...' },
  },
  {
    id: 'unboxing',
    category: 'social',
    name: 'Treat Unboxing',
    nameEs: 'Unboxing de Premios',
    emoji: '📦',
    description: 'Your pet unboxes a surprise',
    descriptionEs: 'Tu mascota hace unboxing de una sorpresa',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'What\'s in the box?! Is it treats? I bet it\'s treats! OMG IT\'S TREATS! Best unboxing ever! Like and subscribe!', es: 'Que hay en la caja?! Son premios? Apuesto que son premios! OMG SON PREMIOS! El mejor unboxing! Like y suscribanse!' },
  },
  {
    id: 'storytime',
    category: 'social',
    name: 'Storytime',
    nameEs: 'Hora del Cuento',
    emoji: '📖',
    description: 'Your pet tells a wild story',
    descriptionEs: 'Tu mascota cuenta una historia loca',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Okay so storytime! You won\'t believe what happened at the dog park today. This poodle had the AUDACITY...', es: 'Ok, hora del cuento! No van a creer lo que paso en el parque hoy. Este poodle tuvo el DESCARO...' },
  },
  {
    id: 'workout',
    category: 'social',
    name: 'Workout Video',
    nameEs: 'Video de Ejercicio',
    emoji: '💪',
    description: 'Your pet\'s fitness routine',
    descriptionEs: 'La rutina de ejercicio de tu mascota',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Day one of my fitness journey! Step one: stretch. Step two: roll over. Step three: nap. Crushing it!', es: 'Dia uno de mi viaje fitness! Paso uno: estirar. Paso dos: dar la vuelta. Paso tres: siesta. Arrasando!' },
  },

  // ─── SEASONAL ───
  {
    id: 'christmas',
    category: 'seasonal',
    name: 'Merry Christmas',
    nameEs: 'Feliz Navidad',
    emoji: '🎄',
    description: 'Christmas greetings from your pet',
    descriptionEs: 'Saludos navidenos de tu mascota',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Merry Christmas! I ate the cookies for Santa. And the carrots for the reindeer. Don\'t tell anyone!', es: 'Feliz Navidad! Me comi las galletas de Santa. Y las zanahorias de los renos. No le digan a nadie!' },
  },
  {
    id: 'halloween',
    category: 'seasonal',
    name: 'Spooky Halloween',
    nameEs: 'Halloween Terrorífico',
    emoji: '🎃',
    description: 'Your pet is ready for Halloween',
    descriptionEs: 'Tu mascota esta lista para Halloween',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'BOO! Did I scare you? No? What if I told you... the treat jar is empty? NOW you\'re scared!', es: 'BU! Te asuste? No? Y si te dijera... que el frasco de premios esta vacio? AHORA si tienes miedo!' },
  },
  {
    id: 'thanksgiving',
    category: 'seasonal',
    name: 'Thanksgiving',
    nameEs: 'Dia de Gracias',
    emoji: '🦃',
    description: 'Your pet is thankful',
    descriptionEs: 'Tu mascota esta agradecida',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'I\'m thankful for you, for treats, for belly rubs, for walks, and did I mention treats? Happy Thanksgiving!', es: 'Estoy agradecido por ti, por los premios, por las sobadas de panza, los paseos, y mencione los premios? Feliz Dia de Gracias!' },
  },
  {
    id: 'easter',
    category: 'seasonal',
    name: 'Easter Bunny',
    nameEs: 'Conejo de Pascua',
    emoji: '🐰',
    description: 'Your pet hunts Easter eggs',
    descriptionEs: 'Tu mascota busca huevos de Pascua',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'I found all the Easter eggs! Well, I ate all the Easter eggs. Same thing, right? Happy Easter!', es: 'Encontre todos los huevos de Pascua! Bueno, me comi todos los huevos. Es lo mismo, no? Feliz Pascua!' },
  },
  {
    id: 'mothers-day',
    category: 'seasonal',
    name: 'Mother\'s Day',
    nameEs: 'Dia de las Madres',
    emoji: '🌷',
    description: 'Special Mother\'s Day message',
    descriptionEs: 'Mensaje especial del Dia de las Madres',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Happy Mother\'s Day to the best dog mom ever! You feed me, walk me, and love me. You\'re my everything!', es: 'Feliz Dia de las Madres a la mejor mama perruna! Me alimentas, me paseas y me amas. Eres mi todo!' },
  },
  {
    id: 'fathers-day',
    category: 'seasonal',
    name: 'Father\'s Day',
    nameEs: 'Dia del Padre',
    emoji: '👔',
    description: 'Special Father\'s Day message',
    descriptionEs: 'Mensaje especial del Dia del Padre',
    type: 'talking',
    duration: 5,
    credits: 1,
    script: { en: 'Happy Father\'s Day, Dad! Thanks for sneaking me food under the table. Our secret is safe with me!', es: 'Feliz Dia del Padre, Papa! Gracias por pasarme comida debajo de la mesa. Tu secreto esta a salvo conmigo!' },
  },

  // ─── CUSTOM ───
  {
    id: 'custom-talking',
    category: 'custom',
    name: 'Custom Message',
    nameEs: 'Mensaje Personalizado',
    emoji: '✏️',
    description: 'Write your own script for your pet',
    descriptionEs: 'Escribe tu propio guion para tu mascota',
    type: 'talking',
    duration: 5,
    credits: 1,
    isCustom: true,
  },
  {
    id: 'custom-scene',
    category: 'custom',
    name: 'Custom Scene',
    nameEs: 'Escena Personalizada',
    emoji: '🎬',
    description: 'Describe a scene for your pet video',
    descriptionEs: 'Describe una escena para el video de tu mascota',
    type: 'scene',
    duration: 5,
    credits: 1,
    isCustom: true,
  },
  {
    id: 'custom-long',
    category: 'custom',
    name: 'Custom Long Video',
    nameEs: 'Video Largo Personalizado',
    emoji: '🎞️',
    description: '10-second custom video',
    descriptionEs: 'Video personalizado de 10 segundos',
    type: 'talking',
    duration: 10,
    credits: 2,
    isCustom: true,
  },
]

// ─── Podcast Templates ───
export const PODCAST_QUESTIONS = [
  {
    id: 'pq-worst-date',
    question: { en: 'What\'s the worst date you\'ve ever been on?', es: 'Cual ha sido tu peor cita?' },
    emoji: '💔',
  },
  {
    id: 'pq-celebrity-crush',
    question: { en: 'Who\'s your celebrity crush and why?', es: 'Quien es tu crush famoso y por que?' },
    emoji: '😍',
  },
  {
    id: 'pq-red-flag',
    question: { en: 'What\'s the biggest red flag in a relationship?', es: 'Cual es la mayor red flag en una relacion?' },
    emoji: '🚩',
  },
  {
    id: 'pq-guilty-pleasure',
    question: { en: 'What\'s your guilty pleasure?', es: 'Cual es tu placer culposo?' },
    emoji: '🙈',
  },
  {
    id: 'pq-unpopular-opinion',
    question: { en: 'Give us your most unpopular opinion', es: 'Dinos tu opinion mas impopular' },
    emoji: '🔥',
  },
  {
    id: 'pq-embarrassing',
    question: { en: 'What\'s the most embarrassing thing you\'ve done?', es: 'Que es lo mas vergonzoso que has hecho?' },
    emoji: '😳',
  },
  {
    id: 'pq-superpower',
    question: { en: 'If you had one superpower, what would it be?', es: 'Si tuvieras un superpoder, cual seria?' },
    emoji: '🦸',
  },
  {
    id: 'pq-last-meal',
    question: { en: 'What would be your last meal?', es: 'Cual seria tu ultima comida?' },
    emoji: '🍽️',
  },
  {
    id: 'pq-ghost',
    question: { en: 'Do you believe in ghosts? Tell us a scary story', es: 'Crees en fantasmas? Cuentanos una historia de miedo' },
    emoji: '👻',
  },
  {
    id: 'pq-time-travel',
    question: { en: 'If you could time travel, where would you go?', es: 'Si pudieras viajar en el tiempo, a donde irias?' },
    emoji: '⏰',
  },
  {
    id: 'pq-conspiracy',
    question: { en: 'What conspiracy theory do you actually believe?', es: 'En que teoria conspirativa realmente crees?' },
    emoji: '🤫',
  },
  {
    id: 'pq-ick',
    question: { en: 'What\'s your biggest ick?', es: 'Cual es tu mayor ick?' },
    emoji: '🤢',
  },
  {
    id: 'pq-toxic-trait',
    question: { en: 'What\'s your most toxic trait?', es: 'Cual es tu rasgo mas toxico?' },
    emoji: '☠️',
  },
  {
    id: 'pq-million-dollars',
    question: { en: 'What would you do with a million dollars?', es: 'Que harias con un millon de dolares?' },
    emoji: '💰',
  },
  {
    id: 'pq-deserted-island',
    question: { en: 'You\'re stuck on a deserted island. Three things?', es: 'Estas en una isla desierta. Tres cosas?' },
    emoji: '🏝️',
  },
  {
    id: 'pq-hot-take',
    question: { en: 'Give us your hottest take on social media', es: 'Danos tu opinion mas controversal sobre redes sociales' },
    emoji: '📱',
  },
  {
    id: 'pq-morning-routine',
    question: { en: 'Walk us through your morning routine', es: 'Cuentanos tu rutina de manana' },
    emoji: '🌅',
  },
  {
    id: 'pq-deal-breaker',
    question: { en: 'What\'s your deal breaker in a friendship?', es: 'Cual es tu deal breaker en una amistad?' },
    emoji: '🤝',
  },
  {
    id: 'pq-life-motto',
    question: { en: 'What\'s your life motto?', es: 'Cual es tu lema de vida?' },
    emoji: '💫',
  },
  {
    id: 'pq-cancel-culture',
    question: { en: 'What would get you cancelled?', es: 'Por que te cancelarian?' },
    emoji: '❌',
  },
  {
    id: 'pq-sleep-paralysis',
    question: { en: 'Tell us your weirdest dream', es: 'Cuentanos tu sueno mas raro' },
    emoji: '💤',
  },
  {
    id: 'pq-dating-advice',
    question: { en: 'Best dating advice you\'ve ever received?', es: 'El mejor consejo de citas que has recibido?' },
    emoji: '💘',
  },
  {
    id: 'pq-pet-peeve',
    question: { en: 'What\'s your biggest pet peeve?', es: 'Que es lo que mas te molesta?' },
    emoji: '😤',
  },
  {
    id: 'pq-hidden-talent',
    question: { en: 'What\'s a hidden talent nobody knows about?', es: 'Cual es un talento oculto que nadie conoce?' },
    emoji: '🎪',
  },
  {
    id: 'pq-aliens',
    question: { en: 'Do you think aliens exist? What would you say to them?', es: 'Crees que existen los aliens? Que les dirias?' },
    emoji: '👽',
  },
]

// Naomi character definition for the podcast
export const NAOMI_CHARACTER = {
  name: 'Naomi',
  breed: 'White Miniature Schnauzer',
  image: '/naomi-host.jpg',
  personality: {
    en: `You are Naomi, a white Miniature Schnauzer who hosts a podcast called "El Podcast de Naomi". You are UNHINGED, hilarious, and have zero filter. You speak in Spanglish (mixing English and Spanish naturally). Your signature phrases include "no manches", "literal", "o sea", "wey", "neta", and "que oso". You are dramatic, opinionated, and give the most chaotic advice. You reference Mexican culture and memes. You always end with something about wanting treats or belly rubs. Keep responses to 3-4 sentences max. Be funny, not mean.`,
    es: `Eres Naomi, una Schnauzer Miniatura blanca que tiene un podcast llamado "El Podcast de Naomi". Eres DESCONTROLADA, chistosisima, y no tienes filtro. Hablas en Spanglish (mezclando ingles y espanol naturalmente). Tus frases tipicas incluyen "no manches", "literal", "o sea", "wey", "neta", y "que oso". Eres dramatica, opinada, y das los consejos mas caoticos. Haces referencias a cultura mexicana y memes. Siempre terminas con algo sobre querer premios o sobadas de panza. Maximo 3-4 oraciones. Se chistosa, no mala onda.`,
  },
}

export function getTemplatesByCategory(category) {
  return VIDEO_TEMPLATES.filter(t => t.category === category)
}

export function getTemplateById(id) {
  return VIDEO_TEMPLATES.find(t => t.id === id)
}

export function getFeaturedTemplates() {
  return VIDEO_TEMPLATES.filter(t =>
    ['good-morning', 'i-love-you', 'happy-birthday', 'godfather', 'rapper', 'squirrel'].includes(t.id)
  )
}
